### ISSUE TITLE
packages/apps/Settings/Evolver/src/org/evolution/settings/fragments/notifications/Notifications.java:50

### ISSUE THREAD

**Issue by Lromdev** [Evolution-XYZ/packages_apps_Settings#1]
packages/apps/Settings/Evolver/src/org/evolution/settings/fragments/notifications/Notifications.java:50: error: cannot find symbol
        mAlertSliderCat = findPreference(ALERT_SLIDER_CAT);
        ^
  symbol:   variable mAlertSliderCat
  location: class Notifications
packages/apps/Settings/Evolver/src/org/evolution/settings/fragments/notifications/Notifications.java:50: error: cannot find symbol
        mAlertSliderCat = findPreference(ALERT_SLIDER_CAT);
                                         ^
  symbol:   variable ALERT_SLIDER_CAT
  location: class Notifications
packages/apps/Settings/Evolver/src/org/evolution/settings/fragments/notifications/Notifications.java:51: error: cannot find symbol
        boolean mAlertSliderAvailable = res.getBoolean(
                                        ^
  symbol:   variable res
  location: class Notifications
packages/apps/Settings/Evolver/src/org/evolution/settings/fragments/notifications/Notifications.java:54: error: cannot find symbol
            prefScreen.removePreference(mAlertSliderCat);
                                        ^
  symbol:   variable mAlertSliderCat
  location: class Notifications
4 errors

**Comment by joeyhuab** [comment]
Already addressed. Kindly send issues in discord for now. Source is still WIP.
